# SPDX-FileCopyrightText: (C) 2026 Deskflow Developers
# SPDX-License-Identifier: MIT

name: Windows package

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-x64:
    name: windows-2022-x64
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup VC++ environment
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: amd64
          spectre: true

      - name: Install dependencies
        id: get-deps
        uses: ./.github/actions/install-dependencies
        with:
          qt-version: 6.11.2
          vcpkg-triplet: x64-windows-release

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: >-
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DSKIP_BUILD_TESTS=ON
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -G Ninja
          ${{ steps.get-deps.outputs.vcpkg-cmake-config }}
          -DPACKAGE_VERSION_LABEL="${{ env.DESKFLOW_PACKAGE_VERSION }}"

      - name: Package
        run: cmake --build build --config Release -j8 --target package

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: package-deskflow-windows-2022-x64
          path: ${{ github.workspace }}/build/deskflow[-_]*.*
          if-no-files-found: error
